# Generated by Django 6.0.6 on 2026-06-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0003_alter_image_site'),
        ('sites_core', '0003_alter_navigationlink_site_alter_redirect_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('commercial', 'Commercial'), ('rare', 'Rare'), ('participation', 'Participation'), ('other', 'Other')], default='commercial', max_length=40)),
                ('description_html', models.TextField(blank=True)),
                ('credits_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('payload_credits', models.JSONField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('shop_url', models.URLField(blank=True)),
                ('bandcamp_url', models.URLField(blank=True)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_images', models.ManyToManyField(blank=True, related_name='album_additional_uses', to='media_library.image')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.artist')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('written_date', models.DateField(blank=True, null=True)),
                ('composer', models.CharField(blank=True, max_length=255)),
                ('lyricist', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('description_html', models.TextField(blank=True)),
                ('lyrics_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('payload_lyrics', models.JSONField(blank=True, null=True)),
                ('shop_link', models.URLField(blank=True)),
                ('streaming_links', models.JSONField(blank=True, default=list)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('disc_number', models.PositiveIntegerField(default=1)),
                ('track_number', models.PositiveIntegerField()),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('version_type', models.CharField(choices=[('studio', 'Studio'), ('live', 'Live'), ('remix', 'Remix'), ('demo', 'Demo')], default='studio', max_length=40)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.song')),
            ],
            options={
                'ordering': ['album', 'disc_number', 'track_number'],
            },
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('video_id', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_artist_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_album_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_album_payload_id_per_site'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_song_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_song_payload_id_per_site'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('album', 'disc_number', 'track_number'), name='unique_track_position_per_album'),
        ),
        migrations.AddConstraint(
            model_name='videoclip',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_videoclip_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='videoclip',
            constraint=models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_videoclip_payload_id_per_site'),
        ),
    ]
