# Generated by Django 6.0.6 on 2026-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_image_site'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='+', to='media_library.image'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('payload_id',), name='unique_track_payload_id'),
        ),
    ]
