# Generated by Django 6.0.6 on 2026-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_additional_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
