# Generated by Django 6.0.6 on 2026-06-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_videoclip_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_date', 'title'], 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'verbose_name': 'artiste', 'verbose_name_plural': 'artistes'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title'], 'verbose_name': 'chanson', 'verbose_name_plural': 'chansons'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['album', 'disc_number', 'track_number'], 'verbose_name': 'piste', 'verbose_name_plural': 'pistes'},
        ),
        migrations.AlterModelOptions(
            name='videoclip',
            options={'ordering': ['-release_date', 'title'], 'verbose_name': 'clip vidéo', 'verbose_name_plural': 'clips vidéo'},
        ),
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('rare', 'Rare'), ('participation', 'Participation'), ('other', 'Autre')], default='commercial', max_length=40),
        ),
    ]
