# Generated by Django 6.0.6 on 2026-07-30 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0004_alter_image_options_alter_imagevariant_options_and_more'),
        ('music', '0004_alter_album_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclip',
            name='description_html',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='payload_description',
            field=models.JSONField(blank=True, null=True, verbose_name='description Payload'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='payload_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Payload'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image', verbose_name='miniature'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='title',
            field=models.CharField(max_length=255, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID vidéo YouTube'),
        ),
    ]
