# Generated by Django 6.0.6 on 2026-06-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0003_alter_image_site'),
        ('sites_core', '0003_alter_navigationlink_site_alter_redirect_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'ordering': ['-date', 'title'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_event_slug_per_site'), models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_event_payload_id_per_site')],
            },
        ),
        migrations.CreateModel(
            name='KeyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'ordering': ['-date', 'title'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_keydate_slug_per_site'), models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_keydate_payload_id_per_site')],
            },
        ),
    ]
