# Generated by Django 6.0.6 on 2026-06-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'date', 'verbose_name_plural': 'dates'},
        ),
        migrations.AlterModelOptions(
            name='keydate',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'date clé', 'verbose_name_plural': 'dates clés'},
        ),
    ]
