# Generated by Django 6.0.6 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_options_alter_keydate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="hide_time",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="location_details",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
