# Generated by Django 6.0.6 on 2026-07-29 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_end_date_event_hide_time_event_url_and_more'),
        ('media_library', '0004_alter_image_options_alter_imagevariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_html',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hide_time',
            field=models.BooleanField(default=False, verbose_name="masquer l'heure"),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_details',
            field=models.CharField(blank=True, max_length=500, verbose_name='lieu / ville'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payload_description',
            field=models.JSONField(blank=True, null=True, verbose_name='description Payload'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payload_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Payload'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='keydate',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='keydate',
            name='description_html',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='keydate',
            name='payload_description',
            field=models.JSONField(blank=True, null=True, verbose_name='description Payload'),
        ),
        migrations.AlterField(
            model_name='keydate',
            name='payload_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Payload'),
        ),
        migrations.AlterField(
            model_name='keydate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='titre'),
        ),
    ]
