# Generated by Django 6.0.6 on 2026-06-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0003_alter_image_site'),
        ('sites_core', '0003_alter_navigationlink_site_alter_redirect_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('adult', 'Adulte'), ('youth', 'Jeunesse'), ('other', 'Other')], default='adult', max_length=60)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('illustrator', models.CharField(blank=True, max_length=255)),
                ('description_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('shop_url', models.URLField(blank=True)),
                ('publisher_url', models.URLField(blank=True)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_images', models.ManyToManyField(blank=True, related_name='bd_additional_uses', to='media_library.image')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'verbose_name': 'BD',
                'verbose_name_plural': 'BDs',
                'ordering': ['-release_date', 'title'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_bd_slug_per_site'), models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_bd_payload_id_per_site')],
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='drawing_uses', to='media_library.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_drawing_slug_per_site'), models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_drawing_payload_id_per_site')],
            },
        ),
    ]
