# Generated by Django 6.0.6 on 2026-06-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0002_alter_bd_additional_images_alter_drawing_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={'ordering': ['-release_date', 'title'], 'verbose_name': 'dessin', 'verbose_name_plural': 'dessins'},
        ),
        migrations.AlterField(
            model_name='bd',
            name='category',
            field=models.CharField(choices=[('adult', 'Adulte'), ('youth', 'Jeunesse'), ('other', 'Autre')], default='adult', max_length=60),
        ),
    ]
