# Generated by Django 6.0.6 on 2026-06-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0003_alter_image_site'),
        ('sites_core', '0003_alter_navigationlink_site_alter_redirect_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('content_html', models.TextField(blank=True)),
                ('content_plain', models.TextField(blank=True)),
                ('payload_content', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('press', 'Press'), ('coup-de-coeur', 'Coup de coeur'), ('other', 'Other')], default='news', max_length=60)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'ordering': ['-published_at', 'title'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_article_slug_per_site'), models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_article_payload_id_per_site')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('novels', 'Romans'), ('illustrated', 'Livres illustres'), ('children', 'Jeunesse'), ('essays', 'Essais'), ('other', 'Other')], default='novels', max_length=60)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('illustrator', models.CharField(blank=True, max_length=255)),
                ('short_description_html', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('payload_short_description', models.JSONField(blank=True, null=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('shop_url', models.URLField(blank=True)),
                ('publisher_url', models.URLField(blank=True)),
                ('show_on_books_page', models.BooleanField(default=True)),
                ('show_on_drawings_page', models.BooleanField(default=False)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_images', models.ManyToManyField(blank=True, related_name='book_additional_uses', to='media_library.image')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_book_slug_per_site'), models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_book_payload_id_per_site')],
            },
        ),
    ]
