# Generated by Django 6.0.6 on 2026-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_image_site'),
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_plain',
            field=models.TextField(blank=True, help_text='Importer-maintained plain text extracted from content_html for search.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='+', to='media_library.image'),
        ),
    ]
