# Generated by Django 6.0.6 on 2026-06-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_alter_article_content_plain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('novels', 'Romans'), ('illustrated', 'Livres illustres'), ('children', 'Jeunesse'), ('essays', 'Essais'), ('misc', 'Divers'), ('other', 'Other')], default='novels', max_length=60),
        ),
    ]
