# Generated by Django 6.0.6 on 2026-06-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_alter_book_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', 'title'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-release_date', 'title'], 'verbose_name': 'livre', 'verbose_name_plural': 'livres'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'Actualités'), ('press', 'Presse'), ('coup-de-coeur', 'Coup de coeur'), ('other', 'Autre')], default='news', max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('novels', 'Romans'), ('illustrated', 'Livres illustrés'), ('children', 'Jeunesse'), ('essays', 'Essais'), ('misc', 'Divers'), ('other', 'Autre')], default='novels', max_length=60),
        ),
    ]
