# Generated by Django 6.0.6 on 2026-07-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0004_alter_image_options_alter_imagevariant_options_and_more'),
        ('writing', '0004_alter_article_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'Actualités'), ('press', 'Presse'), ('coup-de-coeur', 'Coup de coeur'), ('other', 'Autre')], default='news', max_length=60, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_plain',
            field=models.TextField(blank=True, help_text='Importer-maintained plain text extracted from content_html for search.', verbose_name='texte brut'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='description SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='titre SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='payload_content',
            field=models.JSONField(blank=True, null=True, verbose_name='contenu Payload'),
        ),
        migrations.AlterField(
            model_name='article',
            name='payload_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Payload'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='titre'),
        ),
    ]
