# Generated by Django 6.0.6 on 2026-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_alter_article_category_alter_article_content_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('journal', 'Journal'), ('news', 'Actualités'), ('press', 'Presse'), ('coup-de-coeur', 'Coup de coeur'), ('other', 'Autre')], default='news', max_length=60, verbose_name='catégorie'),
        ),
    ]
