# Generated by Django 6.0.6 on 2026-06-21 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
        ('sites_core', '0004_sitesettings_homepage_hero_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('subscribed', 'Subscribed'), ('error', 'Sync error')], default='subscribed', max_length=20)),
                ('source', models.CharField(default='homepage', max_length=80)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('site', 'email'), name='unique_newsletter_email_per_site')],
            },
        ),
    ]
