# Generated by Django 6.0.6 on 2026-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='notification_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
