# Generated by Django 6.0.6 on 2026-06-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0003_contactsubmission_notification_error_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'message de contact', 'verbose_name_plural': 'messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-updated_at'], 'verbose_name': 'inscription newsletter', 'verbose_name_plural': 'inscriptions newsletter'},
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='notification_error',
            field=models.TextField(blank=True, verbose_name='erreur de notification'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='notification envoyée le'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('reviewed', 'Lu'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='dernière erreur'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière synchronisation'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='status',
            field=models.CharField(choices=[('subscribed', 'Inscrit'), ('error', 'Erreur de synchronisation')], default='subscribed', max_length=20, verbose_name='statut'),
        ),
    ]
