# Generated by Django 6.0.6 on 2026-06-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0003_alter_image_site'),
        ('sites_core', '0003_alter_navigationlink_site_alter_redirect_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('photographer', models.CharField(blank=True, max_length=255)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PhotoCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_collections', to='sites_core.site')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PhotoCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='photos.photocollection')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='photos.photo')),
            ],
            options={
                'ordering': ['collection', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='photocollection',
            name='photos',
            field=models.ManyToManyField(blank=True, through='photos.PhotoCollectionItem', to='photos.photo'),
        ),
        migrations.CreateModel(
            name='PhotoStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description_html', models.TextField(blank=True)),
                ('payload_description', models.JSONField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('photographer', models.CharField(blank=True, max_length=255)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'verbose_name_plural': 'photo stories',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_photo_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_photo_payload_id_per_site'),
        ),
        migrations.AddConstraint(
            model_name='photocollectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'photo'), name='unique_photo_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='photocollection',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_photocollection_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='photocollection',
            constraint=models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_photocollection_payload_id_per_site'),
        ),
        migrations.AddConstraint(
            model_name='photostory',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_photostory_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='photostory',
            constraint=models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_photostory_payload_id_per_site'),
        ),
    ]
