# Generated by Django 6.0.6 on 2026-06-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photostory",
            old_name="photo",
            new_name="image",
        ),
    ]
