# Generated by Django 6.0.6 on 2026-06-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_photostory_photo_to_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='photocollection',
            options={'ordering': ['title'], 'verbose_name': 'collection de photos', 'verbose_name_plural': 'collections de photos'},
        ),
        migrations.AlterModelOptions(
            name='photocollectionitem',
            options={'ordering': ['collection', 'order', 'id'], 'verbose_name': 'photo de collection', 'verbose_name_plural': 'photos de collection'},
        ),
        migrations.AlterModelOptions(
            name='photostory',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'histoire de photo', 'verbose_name_plural': 'histoires de photos'},
        ),
    ]
