# Generated by Django 6.0.6 on 2026-06-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='status_code',
            field=models.PositiveSmallIntegerField(choices=[(301, '301 Moved Permanently'), (302, '302 Found'), (307, '307 Temporary Redirect'), (308, '308 Permanent Redirect')], default=301),
        ),
    ]
