# Generated by Django 6.0.6 on 2026-06-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_core', '0002_alter_redirect_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site'),
        ),
    ]
