# Generated by Django 6.0.6 on 2026-06-20 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_image_site'),
        ('sites_core', '0003_alter_navigationlink_site_alter_redirect_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_button_text',
            field=models.CharField(blank=True, help_text='Falls back to “(Re)Découvrir” when left blank.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_button_url',
            field=models.CharField(default='/a-propos', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_text',
            field=models.TextField(blank=True, help_text='Falls back to the default Kent introduction when left blank.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_homepage_hero',
            field=models.BooleanField(default=False),
        ),
    ]
