# Generated by Django 6.0.6 on 2026-06-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites_core', '0004_sitesettings_homepage_hero_button_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationlink',
            options={'ordering': ['site', 'order', 'label'], 'verbose_name': 'lien de navigation', 'verbose_name_plural': 'liens de navigation'},
        ),
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ['site', 'old_path'], 'verbose_name': 'redirection', 'verbose_name_plural': 'redirections'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'réglages du site', 'verbose_name_plural': 'réglages du site'},
        ),
    ]
