# Generated by Django 6.0.6 on 2026-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_core', '0005_alter_navigationlink_options_alter_redirect_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bandcamp_url',
            field=models.URLField(blank=True),
        ),
    ]
