# Generated by Django 6.0.6 on 2026-06-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_core', '0007_populate_kent_social_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_intro_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=160)),
                ('text', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site')),
            ],
            options={
                'verbose_name': 'texte éditorial',
                'verbose_name_plural': 'textes éditoriaux',
                'ordering': ['site', 'label'],
                'constraints': [models.UniqueConstraint(fields=('site', 'key'), name='unique_text_snippet_key_per_site')],
            },
        ),
    ]
