# Generated by Django 6.0.6 on 2026-06-22 19:53

import sites_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_core', '0009_populate_kent_editable_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='apple_touch_icon',
            field=models.FileField(blank=True, help_text='Optional iOS home-screen icon.', upload_to=sites_core.models.site_settings_file_upload_to),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_ico',
            field=models.FileField(blank=True, help_text='Optional .ico or PNG favicon fallback for this site.', upload_to=sites_core.models.site_settings_file_upload_to),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_svg',
            field=models.FileField(blank=True, help_text='Optional SVG favicon for this site.', upload_to=sites_core.models.site_settings_file_upload_to),
        ),
    ]
