# Generated by Django 6.0.6 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_core", "0010_sitesettings_apple_touch_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="dates_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="dates_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
