# Generated by Django 6.0.6 on 2026-07-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_core', '0011_sitesettings_dates_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dates_secondary_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='titre secondaire des dates'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dates_description',
            field=models.TextField(blank=True, verbose_name='description des dates'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dates_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='titre des dates'),
        ),
    ]
