# Generated by Django 6.0.6 on 2026-07-30 08:51

import django.db.models.deletion
import sites_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0004_alter_image_options_alter_imagevariant_options_and_more'),
        ('sites_core', '0013_populate_kent_about_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='apple_touch_icon',
            field=models.FileField(blank=True, help_text="Icône optionnelle pour l'écran d'accueil iOS.", upload_to=sites_core.models.site_settings_file_upload_to, verbose_name='icône Apple Touch'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bandcamp_url',
            field=models.URLField(blank=True, verbose_name='URL Bandcamp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_intro_text',
            field=models.TextField(blank=True, verbose_name='texte contact'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='titre contact'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon_ico',
            field=models.FileField(blank=True, help_text='Favicon .ico ou PNG optionnel en fallback.', upload_to=sites_core.models.site_settings_file_upload_to, verbose_name='favicon ICO/PNG'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon_svg',
            field=models.FileField(blank=True, help_text='Favicon SVG optionnel pour ce site.', upload_to=sites_core.models.site_settings_file_upload_to, verbose_name='favicon SVG'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='texte du pied de page'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_hero_button_text',
            field=models.CharField(blank=True, help_text='Utilise "(Re)Découvrir" si le champ est vide.', max_length=80, verbose_name="texte du bouton d'accueil"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_hero_button_url',
            field=models.CharField(default='/a-propos', max_length=500, verbose_name="lien du bouton d'accueil"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.image', verbose_name="image d'accueil"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_hero_text',
            field=models.TextField(blank=True, help_text="Utilise le texte d'introduction par défaut si le champ est vide.", verbose_name="texte d'accueil"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='URL Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='newsletter_text',
            field=models.TextField(blank=True, verbose_name='texte newsletter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_homepage_hero',
            field=models.BooleanField(default=False, verbose_name="afficher l'image d'accueil"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites_core.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='URL YouTube'),
        ),
    ]
