# Generated by Django 6.0.6 on 2026-09-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0005_alter_image_alt_text_alter_image_caption_and_more'),
        ('sites_core', '0014_alter_sitesettings_apple_touch_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dates_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.image', verbose_name='image de la section dates'),
        ),
    ]
