# Generated by Django 6.0.6 on 2026-06-18 19:46

import django.db.models.deletion
import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_core', '0002_alter_redirect_status_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('original', models.ImageField(blank=True, upload_to=media_library.models.image_original_upload_path)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('filesize', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('payload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_url', models.URLField(blank=True, max_length=1000)),
                ('payload_thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('payload_created_at', models.DateTimeField(blank=True, null=True)),
                ('payload_updated_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sites_core.site')),
            ],
            options={
                'ordering': ['site', 'title', 'filename', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('thumbnail', 'Thumbnail'), ('square', 'Square'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'XLarge'), ('og', 'Open Graph'), ('other', 'Other')], max_length=40)),
                ('file', models.ImageField(blank=True, upload_to=media_library.models.image_variant_upload_path)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('filesize', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('payload_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media_library.image')),
            ],
            options={
                'ordering': ['image', 'kind'],
            },
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('site', 'payload_id'), name='unique_image_payload_id_per_site'),
        ),
        migrations.AddConstraint(
            model_name='imagevariant',
            constraint=models.UniqueConstraint(fields=('image', 'kind'), name='unique_image_variant_kind_per_image'),
        ),
    ]
