# Generated by Django 6.0.6 on 2026-06-19 08:09

from django.db import migrations, models


def backfill_payload_kind(apps, schema_editor):
    image_variant = apps.get_model("media_library", "ImageVariant")
    image_variant.objects.filter(payload_kind="").update(payload_kind=models.F("kind"))


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagevariant',
            name='unique_image_variant_kind_per_image',
        ),
        migrations.AddField(
            model_name='imagevariant',
            name='payload_kind',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(backfill_payload_kind, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='imagevariant',
            constraint=models.UniqueConstraint(fields=('image', 'payload_kind'), name='unique_image_variant_payload_kind_per_image'),
        ),
    ]
