# Generated by Django 6.0.6 on 2026-06-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_remove_imagevariant_unique_image_variant_kind_per_image_and_more'),
        ('sites_core', '0003_alter_navigationlink_site_alter_redirect_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites_core.site'),
        ),
    ]
