# Generated by Django 6.0.6 on 2026-06-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_alter_image_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['site', 'title', 'filename', 'id'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='imagevariant',
            options={'ordering': ['image', 'kind'], 'verbose_name': "variante d'image", 'verbose_name_plural': "variantes d'image"},
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='kind',
            field=models.CharField(choices=[('thumbnail', 'Vignette'), ('square', 'Carré'), ('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand'), ('xlarge', 'Très grand'), ('og', 'Open Graph'), ('other', 'Autre')], max_length=40),
        ),
    ]
