# Generated by Django 6.0.6 on 2026-09-02 07:45

import django.db.models.deletion
import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0004_alter_image_options_alter_imagevariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='texte alternatif'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True, verbose_name='légende'),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom du fichier'),
        ),
        migrations.AlterField(
            model_name='image',
            name='filesize',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='taille du fichier'),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='hauteur'),
        ),
        migrations.AlterField(
            model_name='image',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='type MIME'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(blank=True, upload_to=media_library.models.image_original_upload_path, verbose_name='fichier original'),
        ),
        migrations.AlterField(
            model_name='image',
            name='payload_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='créé dans Payload le'),
        ),
        migrations.AlterField(
            model_name='image',
            name='payload_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Payload'),
        ),
        migrations.AlterField(
            model_name='image',
            name='payload_thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL vignette Payload'),
        ),
        migrations.AlterField(
            model_name='image',
            name='payload_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='modifié dans Payload le'),
        ),
        migrations.AlterField(
            model_name='image',
            name='payload_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL Payload'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='largeur'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='file',
            field=models.ImageField(blank=True, upload_to=media_library.models.image_variant_upload_path, verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom du fichier'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='filesize',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='taille du fichier'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='hauteur'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media_library.image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='kind',
            field=models.CharField(choices=[('thumbnail', 'Vignette'), ('square', 'Carré'), ('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand'), ('xlarge', 'Très grand'), ('og', 'Open Graph'), ('other', 'Autre')], max_length=40, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='type MIME'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='payload_kind',
            field=models.CharField(blank=True, max_length=80, verbose_name='type Payload'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='payload_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL Payload'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='imagevariant',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='largeur'),
        ),
    ]
